spring:
  application:
    name: Task-Management-App
  datasource:
    url: jdbc:mysql://localhost:3306/TaskDB
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
