spring:
  application:
    name: Task-Management-App
  datasource:
    url: jdbc:mysql://localhost:3306/TaskDB
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: amr.elhady.programs@gmail.com
    password: rsrn irvh kxiy zxxe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true